version: "2"
services:
  intruders:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx
    depends_on:
      - intruders
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "1567:80"
