version: '2'
services:
  intruders:
    container_name: intruders_be
    build: .
    environment:
      - NODE_ENV=production
      - ENABLE_NODE_LOG=YES
    restart: always
  nginx:
    container_name: nginx_intruders_be
    image: nginx:latest
    depends_on:
      - be
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1567:80"
